# ========================================
# CONFIGURATION DOCKER
# ========================================

server:
  port: ${EUREKA_SERVER_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:eureka-server}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME:eureka-server}:${EUREKA_SERVER_PORT:8761}/eureka/

logging:
  file:
    name: /app/logs/eureka-server.log