services:
  mysql-db:
    image: mysql:8.0
    container_name: graphql-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 112233**
      MYSQL_DATABASE: smart_tourism_graph_ql
      MYSQL_USER: graphql_user
      MYSQL_PASSWORD: graphql123
    ports:
      - "3308:3306"
    volumes:
      - mysql-graphql-data:/var/lib/mysql

  graphql-service:
    build: .
    container_name: graphql-service
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      DB_HOST: host.docker.internal
      DB_NAME: smart_tourism_graph_ql
      DB_USER: root
      DB_PASS: 112233**
      DB_PORT: 3308
      PORT: 4000
      
      # Eureka - supposant qu'Eureka tourne sur votre machine h√¥te
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://host.docker.internal:8761/eureka/"
      EUREKA_INSTANCE_HOSTNAME: localhost
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql-db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: graphql-phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql-db
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 512M
    ports:
      - "8083:80"

volumes:
  mysql-graphql-data: