server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      routes:
        # Route pour attractions-service (REST)
        - id: attractions-service
          uri: lb://ATTRACTIONS-SERVICE
          predicates:
            - Path=/api/attractions/**
          filters:
            - StripPrefix=2  # ⚠️ Changé de 1 à 2 pour enlever /api/attractions
            - name: CircuitBreaker
              args:
                name: attractionsCircuit
                fallbackUri: forward:/fallback/attractions
        
        # Route pour Swagger/OpenAPI
        - id: attractions-swagger
          uri: lb://ATTRACTIONS-SERVICE
          predicates:
            - Path=/api/attractions-service/swagger-ui.html
          filters:
            - SetPath=/swagger-ui.html
        
        - id: attractions-api-docs
          uri: lb://ATTRACTIONS-SERVICE
          predicates:
            - Path=/api/attractions-service/api-docs
          filters:
            - SetPath=/api-docs
        # route WSDL (GET)
        - id: cultural-soap-wsdl
          uri: lb://CULTURAL-SOAP-SERVICE
          predicates:
            - Path=/soap/wsdl/**         # ex: http://localhost:8080/soap/wsdl/culturalArchive.wsdl
          filters:
            - StripPrefix=2              # enlève /soap/wsdl -> envoie /culturalArchive.wsdl au service

        # route pour le endpoint SOAP (POST)
        - id: cultural-soap-endpoint
          uri: lb://CULTURAL-SOAP-SERVICE
          predicates:
            - Path=/soap/ws/**           # ex: http://localhost:8080/soap/ws
          filters:
            - StripPrefix=1              # enlève /soap -> envoie /ws au service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG